var translation = {
	de: {
		light: "hell",
		dark: "dunkel",
		start: "Start",
		portfolio: "Portfolio",
		contact: "Kontakt",
		skills: "Skills",
		projects: "Projekte",
		my_name: "Mischa Rodchenkov",
		position: "Softwareentwickler bei iCode GmbH, Berlin",
		my_bio: "Ich bin in der Ukraine (Krim) am 26. Juni geboren. Ich studiere momentan Wirtschaftsinformatik an der Technische Hochschule Brandenburg. Seit 2017 bin ich bei iCode GmbH als Softwareentwickler tätig. Meine Hobbies sind Reisen und Web Design. Schreiben Sie mir eine Mail, falls ich Ihre Interesse geweckt habe:",
		design_btn: "Design Portfolio",
		list_item: "Projektmanagement (Scrum), Wirtschaftwissenschaften",
		see: "Los",
		closed: "geschlossen",
		p1_desc: "",
		p2_desc: "",
		p3_desc: "",
		p4_desc: "",
		p5_desc: "",
		p6_desc: "",
	},
	en: {
		light: "dark",
		dark: "dark",
		start: "Start",
		portfolio: "Portfolio",
		contact: "Contact",
		skills: "Skills",
		projects: "Projects",
		my_name: "Mischa Rodchenkov",
		position: "Java Software Developer, iCode Berlin",
		my_bio: "Ich bin in der Ukraine (Krim) am 26. Juni geboren. Ich studiere momentan Wirtschaftsinformatik an der Technische Hochschule Brandenburg. Seit 2017 bin ich bei iCode GmbH als Softwareentwickler tätig. Meine Hobbies sind Reisen und Web Design. Schreiben Sie mir eine Mail, falls ich Ihre Interesse geweckt habe:",
		design_btn: "Design Portfolio",
		list_item: "Project management (Scrum), Economics",
		see: "See",
		closed: "Closed",
		p1_desc: "",
		p2_desc: "",
		p3_desc: "",
		p4_desc: "",
		p5_desc: "",
		p6_desc: "",
	},
	ru: {
		light: "день",
		dark: "ночь",
		start: "Старт",
		portfolio: "Портфолио",
		contact: "Контакт",
		skills: "Скилы",
		projects: "Проекты",
		my_name: "Миша Родченков",
		position: "Разработчик программного обеспечения, Берлин",
		my_bio: "Я родился 26. Июня в Крыму, Украина. Учу бизнес информатику в техническом университете в Бранденбурге, Германия. С 2017 года работаю разработчиком в iCode. В свободное время занимаюсь веб дизайном и путешествую. По вопросам и предложениям писать на почту:",
		design_btn: "Портфолио",
		list_item: "Проект менеджмент (Scrum), экономические науки",
		see: "Вперёд",
		closed: "Закрыто",
		p1_desc: "",
		p2_desc: "",
		p3_desc: "",
		p4_desc: "",
		p5_desc: "",
		p6_desc: "",
	}
}