var translation = {
	de: {
		light: 		"hell",
		dark: 		"dunkel",
		start: 		"Start",
		portfolio: 	"Portfolio",
		contact: 	"Kontakt",
		skills: 	"Skills",
		projects: 	"Projekte",
		my_name: 	"Mischa Rodchenkov",
		position: 	"Softwareentwickler bei iCode GmbH, Berlin",
		my_bio: 	"Ich bin in der Ukraine (Krim) im 1993 geboren. Ich studiere momentan Wirtschaftsinformatik an der Technische Hochschule Brandenburg. Seit 2017 bin ich bei iCode GmbH als Softwareentwickler tätig. Meine Hobbies sind Reisen und Web Design. Schreiben Sie mir eine Mail, falls ich Ihre Interesse geweckt habe:",
		design_btn: "Design Portfolio",
		list_item: 	"ISQI Software Projektmanagement Zertifizierung, Oracle Java Bescheinigung",
		see: 		"Los",
		closed: 	"geschlossen",
		readyhire: 	"bereit für Anstellung",
		p1_desc: 	"A small presentation of future website for a hotel (in russian)",
		p2_desc: 	"A web site to note university courses and prepare presentations",
		p3_desc: 	"Small online shop for local supermarkets, developed with CakePHP",
		p4_desc: 	"A programm that generates dynamic prices for hotel rooms based on day",
		p5_desc: 	"Administration Panel for another presence application for small comanies",
		p6_desc: 	"Social network for activities and events with activity-map",
	},
	en: {
		light: 		"dark",
		dark: 		"dark",
		start: 		"Start",
		portfolio: 	"Portfolio",
		contact: 	"Contact",
		skills: 	"Skills",
		projects: 	"Projects",
		my_name: 	"Misha Rodchenkov",
		position: 	"Java Software Developer, iCode Berlin",
		my_bio: 	"I was born in Crimea (Ukraine), 1993. I study business informatics at Univeristy Brandenburg, Germany. I work for iCode since 2017 as Software Developer. My hobbies are wild traveling and Web Design. If you want to get in touch with me for propositions or ask me for SV, write email to:",
		design_btn: "Design Portfolio",
		list_item: 	"ISQI Software Project Management Certificate, Oracle Java Attestation",
		see: 		"See",
		closed: 	"Closed",
		readyhire: 	"Ready to be hired", 
		p1_desc: 	"A small presentation of future website for a hotel (in russian)",
		p2_desc: 	"A web site to note university courses and prepare presentations",
		p3_desc: 	"Small online shop for local supermarkets, developed with CakePHP",
		p4_desc: 	"A programm that generates dynamic prices for hotel rooms based on day",
		p5_desc: 	"Administration Panel for another presence application for small comanies",
		p6_desc: 	"Social network for activities and events with activity-map",
	},
	ru: {
		light: 		"день",
		dark: 		"ночь",
		start: 		"Старт",
		portfolio: 	"Портфолио",
		contact: 	"Контакт",
		skills: 	"Скилы",
		projects: 	"Проекты",
		my_name: 	"Миша Родченков",
		position: 	"Разработчик программного обеспечения, Берлин",
		my_bio: 	"Я родился в 1993 в Крыму, Украина. Учу бизнес информатику в техническом университете в Бранденбурге, Германия. С 2017 года работаю разработчиком в iCode. В свободное время занимаюсь веб дизайном и путешествую. По вопросам и предложениям писать на почту:",
		design_btn: "Портфолио",
		list_item: 	"ISQI Сертификат по проект менеджменту, Oracle Java Аттестат",
		see: 		"Вперёд",
		closed: 	"Закрыто",
		readyhire: 	"готов к трудоустройству",
		p1_desc: 	"Небольшая презентация для будущего сайта отеля",
		p2_desc: 	"Сайт для конспектирования и документирования лекций в университете",
		p3_desc: 	"Маленький онлайн магазин для местных супермаркетов, написан на CakePHP",
		p4_desc: 	"Программа генерирующая динамично цены на комнаты в зависимости от дня",
		p5_desc: 	"Админ панель для программы отслеживающей посещения и время работы персонала",
		p6_desc: 	"Социальная сеть для проектов. Также есть похожая на физическую карта проектов",
	}
}
